# Generated by Django 6.0.6 on 2026-07-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='type',
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('article', 'Статья'), ('news', 'Новость')], default='article', max_length=7),
        ),
    ]
